### ISSUE TITLE
Improve the application of the moo algorithm in paref_moo.py

### ISSUE THREAD

**Issue by SebastianMortag** [nicolaipalm/paref#4]
https://github.com/nicolaipalm/paref/blob/c7293dba2cd4d5b9c61ba19c77e1a93204a7adca/paref/interfaces/moo_algorithms/paref_moo.py#L199-L199

The while loop doesn't accurately count the number of evaluations, since a `break` can stop it before the algorithm is applied.

Possible fix:
SequenceParetoReflections implements the Iterator interface by implementing the __next__ function. Now probe it using `next()` and check for StopIteration in a Try-Except.

**Comment by nicolaipalm** [comment]
I think you refer to the issue that the LHC sampling was not taken into account when the MaxIterationsReached stopping criterion was used. If this is the case it is solved now: the initial sampling is now excluded from the MOOs but rather implemented within the bbf interface - now the initial sampling must be done previous before any MOO (rather than exected within an MOO) which solves this issue.
